 {id:7,name:'Gaming Keyboard',price:1800,cat:'Gaming',icon:'⌨️',meta:'3.0 km · Like new',verified:false},
 {id:8,name:'Hostel Mini Fridge',price:3500,cat:'Hostel Items',icon:'🧊',meta:'1.7 km · Used',verified:true}
];
const cats=[['Books','📚'],['Electronics','🔌'],['Laptops','💻'],['Mobiles','📱'],['Hostel Items','🛏️'],['Furniture','🪑'],['Study Materials','🧮'],['Sports','🏏'],['Clothing','👕'],['Shoes','👟'],['Accessories','🎒'],['Bicycles','🚲'],['Vehicles','🚗'],['Gaming','🎮'],['Services','🛠️'],['Other','✨']];
let wishlist=new Set(JSON.parse(localStorage.getItem('uniloop-wishlist')||'[]'));
const $=s=>document.querySelector(s);
function renderCats(){ $('#catGrid').innerHTML=cats.map(([n,e])=>`<div class="cat" data-cat="${n}"><span class="emoji">${e}</span><span>${n}</span></div>`).join(''); document.querySelectorAll('.cat').forEach(x=>x.onclick=()=>{ $('#filterCat').value=x.dataset.cat; location.hash='explore'; renderProducts(); }); $('#filterCat').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${c[0]}</option>`).join(''); }
function renderProducts(){ let q=($('#search').value||'').toLowerCase(), cat=$('#filterCat').value, type=$('#filterType').value, sort=$('#sort').value; let list=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q))&&(cat==='all'||p.cat===cat)&&(type==='all'||(type==='Verified sellers'&&p.verified)||(type==='Under ₹5,000'&&p.price<5000))); if(sort==='low')list.sort((a,b)=>a.price-b.price); if(sort==='high')list.sort((a,b)=>b.price-a.price); $('#productGrid').innerHTML=list.map(p=>`<article class="product" data-id="${p.id}"><div class="pic">${p.verified?'<span class="badge">✓ Verified Student</span>':''}<button class="heart ${wishlist.has(p.id)?'active':''}" data-wish="${p.id}">${wishlist.has(p.id)?'♥':'♡'}</button>${p.icon}</div><div class="pbody"><h3>${p.name}</h3><div class="price">₹${p.price.toLocaleString('en-IN')}</div><div class="meta">${p.meta} · ${p.cat}</div></div></article>`).join('')||'<div style="grid-column:1/-1;padding:50px;text-align:center;color:#7c8495">No listings match your search.</div>'; document.querySelectorAll('.product').forEach(x=>x.onclick=e=>{if(e.target.closest('.heart'))return;openProduct(+x.dataset.id)}); document.querySelectorAll('.heart').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleWish(+b.dataset.wish)}); }
function toggleWish(id){wishlist.has(id)?wishlist.delete(id):wishlist.add(id);localStorage.setItem('uniloop-wishlist',JSON.stringify([...wishlist]));$('#wishCount').textContent=wishlist.size;renderProducts()}
function openProduct(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="pic" style="height:210px;border-radius:12px;margin-bottom:20px">${p.icon}</div><h2>${p.name}</h2><div class="price">₹${p.price.toLocaleString('en-IN')}</div><p style="color:#687184">${p.meta} · ${p.cat}</p>${p.verified?'<p style="color:#2f8f6e;font-weight:800">✓ Verified Student seller</p>':''}<p style="line-height:1.6;color:#5f687a">Connect with the seller to ask questions, make an offer or arrange a campus-friendly handover.</p><button class="primary" id="chatBtn">Start chat / Make offer</button>`;$('#modal').classList.add('show');$('#chatBtn').onclick=()=>openLogin('Sign in to chat');}
function openLogin(title='Log in to UNI LOOP'){$('#modalContent').innerHTML=`<h2>${title}</h2><p style="color:#6d7587">Use your account to save listings, chat with sellers and unlock student verification.</p><label>Email</label><input type="email" placeholder="you@example.com"><label>Password</label><input type="password" placeholder="••••••••"><button class="primary">Log in</button><p style="text-align:center;color:#8991a3;font-size:12px">Demo UI — connect Firebase Authentication for live accounts.</p>`;$('#modal').classList.add('show')}
function openSell(){ $('#modalContent').innerHTML=`<h2>Sell an item</h2><p style="color:#6d7587">Create a listing and reach people around your campus.</p><label>Item title</label><input placeholder="e.g. HP Laptop 15s"><label>Category</label><select>${cats.map(c=>`<option>${c[0]}</option>`).join('')}</select><label>Price (₹)</label><input type="number" placeholder="2500"><label>Description</label><textarea rows="4" placeholder="Condition, pickup location, details..."></textarea><button class="primary" id="publish">Create listing</button>`;$('#modal').classList.add('show');$('#publish').onclick=()=>{ $('#modalContent').innerHTML='<h2>Listing form ready ✓</h2><p style="color:#687184;line-height:1.6">In the full Next.js project, this form connects to the listing workflow and can be wired to Firebase Storage/Firestore.</p><button class="primary" id="done">Close</button>';$('#done').onclick=closeModal;};}
function closeModal(){$('#modal').classList.remove('show')}
$('#heroSearchBtn').onclick=()=>{$('#search').value=$('#heroSearch').value;location.hash='explore';renderProducts()};$('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#heroSearchBtn').click()});['search','filterCat','filterType','sort'].forEach(id=>$('#'+id).addEventListener('input',renderProducts));$('#wishlistBtn').onclick=()=>{ $('#filterType').value='all'; $('#search').value=''; $('#filterCat').value='all'; location.hash='explore';renderProducts(); };$('#loginBtn').onclick=()=>openLogin();$('#sellTop').onclick=openSell;$('#sellCta').onclick=openSell;$('#footerSell').onclick=openSell;$('#close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#wishCount').textContent=wishlist.size;renderCats();renderProducts();
